services:
  postgres_db:
    networks: 
      - elt_network
    image: postgres:16
    environment:
      POSTGRES_DB: weather_db
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ./source_db_init/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  # ingestion:
  #   networks: 
  #     - elt_network
  #   build: ./ingestion
  #   depends_on:
  #     postgres_db:  
  #       condition: service_healthy
  #       restart: true
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./sales_data:/app/sales_data

  # dbt:
  #   image: ghcr.io/dbt-labs/dbt-postgres:1.7.4
  #   networks: 
  #     - elt_network
  #   volumes:
  #     - ./postgres_transformations/dbt:/usr/app/dbt
  #   environment:
  #     DBT_PROFILE: dbt_weather
  #     DBT_TARGET: dev
  #   entrypoint: ["sh", "-c"]
  #   command: >
  #     "dbt deps --project-dir /usr/app/dbt --profiles-dir /usr/app/dbt &&
  #      dbt run --project-dir /usr/app/dbt --profiles-dir /usr/app/dbt"
  #   depends_on:
  #     postgres_db:
  #       condition: service_healthy
  #     ingestion:
  #       condition: service_completed_successfully

  airflow_db:
    networks:
      - elt_network 
    image: postgres:16
    environment:
      POSTGRES_USER: $AIRFLOW_USER
      POSTGRES_PASSWORD: $AIRFLOW_PASSWORD
      POSTGRES_DB: airflow
    volumes:
      - airflow_db_data:/var/lib/postgresql/data 
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U airflow -d airflow']
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  init-airflow:
    image: apache/airflow:3.2.1
    depends_on:
      airflow_db:
        condition: service_healthy
    networks:
      - elt_network
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=$AIRFLOW_POSTGRES_CONNECTION_STRING
      - AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_PASSWORDS=$AIRFLOW_USER:$AIRFLOW_PASSWORD
    command: >
      bash -c "airflow db migrate"

  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    depends_on:
      airflow_db:
        condition: service_healthy
      init-airflow:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/execution/health"]
      interval: 10s
      retries: 10
      start_period: 30s
      timeout: 10s
    networks:
      - elt_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./ingestion:/opt/airflow/ingestion
      - ./postgres_transformations:/opt/dbt
      - ~/.dbt:/root/.dbt
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - AIRFLOW__CORE__INTERNAL_API_URL=http://webserver:8080
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=$AIRFLOW_POSTGRES_CONNECTION_STRING
      - AIRFLOW_CONN_DESTINATION_POSTGRES=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres_db:5432/weather_db
      - AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_PASSWORDS=$AIRFLOW_USER:$AIRFLOW_PASSWORD
      - AIRFLOW__LOGGING__LOGGING_LEVEL=INFO
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
      - AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK=true
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=False
      - PROJECT_ROOT=$PROJECT_ROOT
      - AIRFLOW__API__SECRET_KEY=$SECRET_KEY
      - AIRFLOW__API_AUTH__JWT_SECRET=$JWT_SECRET
      - AIRFLOW__CORE__FERNET_KEY=$FERNET_KEY
    ports:
      - "8080:8080"
    command: api-server

  scheduler:
    hostname: elt-scheduler-1
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    depends_on:
      airflow_db:
        condition: service_healthy
      init-airflow:
        condition: service_completed_successfully
      webserver:                    
        condition: service_healthy
    networks:
      - elt_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./ingestion:/opt/airflow/ingestion
      - ./postgres_transformations:/opt/dbt
      - ~/.dbt:/root/.dbt
      - /var/run/docker.sock:/var/run/docker.sock
      - ./sales_data:/opt/airflow/sales_data
    environment:
      - AIRFLOW__CORE__INTERNAL_API_URL=http://webserver:8080
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=$AIRFLOW_POSTGRES_CONNECTION_STRING
      - AIRFLOW_CONN_DESTINATION_POSTGRES=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres_db:5432/weather_db
      - AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_PASSWORDS=$AIRFLOW_USER:$AIRFLOW_PASSWORD
      - AIRFLOW__LOGGING__LOGGING_LEVEL=INFO
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
      - AIRFLOW__CORE__EXECUTION_API_SERVER_URL=http://webserver:8080/execution/
      - AIRFLOW__LOGGING__LOGGING_SERVER_HOST=elt-scheduler-1
      - AIRFLOW__LOGGING__LOGGING_SERVER_PORT=8793
      - AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK=true
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=False
      - PROJECT_ROOT=$PROJECT_ROOT
      - AIRFLOW__API__SECRET_KEY=$SECRET_KEY
      - AIRFLOW__API_AUTH__JWT_SECRET=$JWT_SECRET
      - AIRFLOW__CORE__FERNET_KEY=$FERNET_KEY
    command: scheduler

  dag-processor:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    depends_on:
      airflow_db:
        condition: service_healthy
      init-airflow:
        condition: service_completed_successfully
      webserver:                    
        condition: service_healthy
    networks:
      - elt_network
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./ingestion:/opt/airflow/ingestion
      - ./postgres_transformations:/opt/dbt
      - ~/.dbt:/root/.dbt
      - /var/run/docker.sock:/var/run/docker.sock
      - ./sales_data:/opt/airflow/sales_data
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=$AIRFLOW_POSTGRES_CONNECTION_STRING
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=False
      - AIRFLOW__CORE__EXECUTION_API_SERVER_URL=http://webserver:8080/execution/
      - PROJECT_ROOT=$PROJECT_ROOT
      - AIRFLOW__API__SECRET_KEY=$SECRET_KEY
      - AIRFLOW__API_AUTH__JWT_SECRET=$JWT_SECRET
      - AIRFLOW__CORE__FERNET_KEY=$FERNET_KEY
    command: dag-processor

  superset_db:
    networks:
      - elt_network
    image: postgres:16
    environment:
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_DB: superset
    volumes:
      - superset_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U superset -d superset']
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  superset:
    build: 
      context: .
      dockerfile: Dockerfile.superset
    networks:
      - elt_network
    depends_on:
      superset_db:
        condition: service_healthy
      postgres_db:        
        condition: service_healthy
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_SECRET_KEY=$SUPERSET_SECRET_KEY
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://superset:superset@superset_db:5432/superset
      - SUPERSET_CONFIG_PATH=/app/pythonpath/superset_config.py
    volumes:
      - superset_home:/app/superset_home
      - ./superset/superset_config.py:/app/pythonpath/superset_config.py
    command: >
      bash -c "
        superset db upgrade && 
        superset fab create-admin --username admin --firstname Admin --lastname User --email admin@example.com --password admin && 
        superset init &&
        superset run -p 8088 -h 0.0.0.0 --with-threads --reload --debugger
      "

volumes:
  airflow_db_data:
  superset_db_data:
  superset_home:

networks:
  elt_network:
    driver: bridge